config/routes.rb
Rails.application.routes.draw do
  devise_for :recipients, skip: [:registrations,:passwords], controllers: {
    sessions: 'recipient/sessions'
  }
  devise_for :contributors, skip: [:passwords], controllers: {
    registrations: 'contributor/registrations',
    sessions: 'contributor/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done',as: 'done'
  get '/about' => 'homes#about', as: 'about'

  namespace :contributor do
    resource :contributors do
      member do
        get :quit
        patch :out
      end
    end
    resources :posts do
      collection do
        get 'search'
      end
    end
  end

  scope module: :recipient do
    resources :recipients do
      get 'favorites' => 'favorites#index'
      get 'follows' => 'relationships#follows', as: 'follows'
    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
      collection do
        get 'search'
      end
    end
    resources :contributors do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end


  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followers, through: :relationships, source: :recipient
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, :nickname, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contributor
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :requesters, through: :requests, source: :recipient
  has_many :rooms
  attachment :post_image

  validates :contributor_id, :genre, :title, :status, :prefecture, presence: true

  enum prefecture: {
    指定地域なし:1,
    北海道:2,青森県:3,岩手県:4,宮城県:5,秋田県:6,山形県:7,福島県:8,
    茨城県:9,栃木県:10,群馬県:11,埼玉県:12,千葉県:13,東京都:14,神奈川県:15,
    新潟県:16,富山県:17,石川県:18,福井県:19,山梨県:20,長野県:21,
    岐阜県:22,静岡県:23,愛知県:24,三重県:25,
    滋賀県:26,京都府:27,大阪府:28,兵庫県:29,奈良県:30,和歌山県:31,
    鳥取県:32,島根県:33,岡山県:34,広島県:35,山口県:36,
    徳島県:37,香川県:38,愛媛県:39,高知県:40,
    福岡県:41,佐賀県:42,長崎県:43,熊本県:44,大分県:45,宮崎県:46,鹿児島県:47,沖縄県:48
  }

  enum status: {
    非公開:1, 公開:2,決定済み:3
  }

  enum genre: {
    その他:1, 寄付:2, 活動:3
  }

  def favorited_by?(recipient)
    favorites.where(recipient_id: recipient.id).exists?
  end

  def requested_by?(recipient)
    requests.where(recipient_id: recipient.id).exists?
  end

  def created_rooms?(recipient)
    rooms.where(recipient_id: recipient.id).exists?
  end

  def self.search(name, title, prefecture, genre)
    posts = Post.where(status: '公開').order(updated_at: :desc)
    if name.present?
      posts = posts.includes(:contributor).joins(:contributor).where('nickname LIKE?', "%#{name}%")
    end
    if title.present?
      posts = posts.where('title LIKE?', "%#{title}%")
    end
    if genre.present?
      posts = posts.where(genre: genre)
    end
    if prefecture == '1'
      posts
    else
      posts =  posts.where(prefecture: [prefecture, 1])
    end
  end

  def self.search_contributor_post(title, prefecture, genre, status)
    posts = self.order(updated_at: :desc)
    if title.present?
      posts = posts.where('title LIKE?', "%#{title}%")
    end
    if genre.present?
      posts = posts.where(genre: genre)
    end
    if status.present?
      posts = posts.where(status: status)
    end
    if prefecture == '1'
      posts
    else
      posts =  posts.where(prefecture: [prefecture, 1])
    end
  end
end

app/controllers/contributor/confirmations_controller.rb
# frozen_string_literal: true

class Contributor::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/contributor/contributors_controller.rb
class Contributor::ContributorsController < ApplicationController
  before_action :authenticate_contributor!
  
  def show
    @contributor = current_contributor
    @posts = @contributor.posts
  end

  def edit
    @contributor = current_contributor
  end

  def update
    @contributor = current_contributor
    if @contributor.update(contributor_params)
      redirect_to contributor_contributors_path
    else
      render :edit
    end
  end

  def quit
  end

  def out
    @contributor = current_contributor
    @contributor.update(is_active: false)
    reset_session
    redirect_to root_path
  end


  private

  def contributor_params
    params.require(:contributor).permit(:name, :nickname, :email, :organization_name, :organization_url, :profile_image, :introduction)
  end

end

app/controllers/contributor/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Contributor::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/contributor/passwords_controller.rb
# frozen_string_literal: true

class Contributor::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/contributor/posts_controller.rb
class Contributor::PostsController < ApplicationController
    before_action :authenticate_contributor!, exept: [:index]
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.contributor_id = current_contributor.id
    if @post.save
      redirect_to contributor_post_path(@post.id)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @recipients = @post.requesters
    @room = Room.new
  end

  def index
    @contributor = current_contributor
    @posts = @contributor.posts.all.order(updated_at: :desc).page(params[:page]).per(15)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to contributor_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to contributor_posts_path
    else
      render :show
    end
  end

    def search
    @posts = current_contributor.posts.all.search_contributor_post(params[:title], params[:prefecture], params[:genre],params[:status]).page(params[:page]).per(15)
    render :index
  end

  private
  def post_params
    params.require(:post).permit(:title, :genre, :content, :post_image, :status, :prefecture)
  end

end

app/controllers/contributor/registrations_controller.rb
# frozen_string_literal: true

class Contributor::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :organization_name, :organization_url,:profile_image, :introduction])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname, :organization_name, :organization_url,:profile_image, :introduction])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    contributor_contributors_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/contributor/sessions_controller.rb
# frozen_string_literal: true

class Contributor::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_contributor, only:[:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_contributor
    @contributor = Contributor.find_by(email: params[:contributor][:email])
    if @contributor
      if @contributor.valid_password?(params[:contributor][:password]) && !@contributor.is_active
        redirect_to new_contributor_session_path
      end
    end
  end
end

app/controllers/contributor/unlocks_controller.rb
# frozen_string_literal: true

class Contributor::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/recipient/contributors_controller.rb
class Recipient::ContributorsController < ApplicationController
  def show
    @contributor = Contributor.find(params[:id])
    @recipient = current_recipient
    @posts = @contributor.posts.where(status: '公開').order(updated_at: :desc).page(params[:page]).per(15)
  end
end

app/controllers/recipient/posts_controller.rb
class Recipient::PostsController < ApplicationController
  def index
    @posts = Post.where(status: '公開').order(updated_at: :desc).page(params[:page]).per(15)
  end

  def show
    @post = Post.find(params[:id])
    @contributor = @post.contributor
    @recipient = current_recipient
  end

  def search
    @posts = Post.search(params[:name],params[:title], params[:prefecture], params[:genre]).order(updated_at: :desc).page(params[:page]).per(15)
    render :index
  end
end

app/helpers/contributor/contributors_helper.rb
module Contributor::ContributorsHelper
end

app/helpers/contributor/posts_helper.rb
module Contributor::PostsHelper
end

app/helpers/recipient/contributors_helper.rb
module Recipient::ContributorsHelper
end

app/helpers/recipient/posts_helper.rb
module Recipient::PostsHelper
end

app/views/contributor/posts/_form.html.erb
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :genre %><br>
          <%= f.select :genre, Post.genres.keys, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :content %><br>
          <%= f.text_area :content, size: "1x20", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :post_image %><br>
          <%= f.attachment_field :post_image %>
        </div>
        <div class="form-group">
          <%= f.label :status %><br>
          <%= f.select :status, Post.statuses.keys, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :prefecture %><br>
          <%= f.select :prefecture, Post.prefectures.keys, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit '保存', class: "btn btn-success" %>
        </div>

app/views/contributor/posts/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>日付</th>
      <th>タイトル</th>
      <th>地域</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>

      <% posts.each do |post| %>
          <tr>
            <td><%= post.updated_at.to_s(:day_jp) %></td>
            <td><%= link_to contributor_post_path(post) do %><%= post.title %><% end %></td>
            <td><%= post.prefecture %></td>
            <td><%= post.genre %></td>
            <td><%= post.status %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/contributor/posts/edit.html.erb
<div class="container">
  <div class ="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @post, url: contributor_post_path(@post), method: :patch, local: true do |form| %>
        <%= render 'form' ,f: form %>
      <% end %>
    </div>
  </div>
</div>

app/views/contributor/posts/index.html.erb
<div class="container px-3 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <h4 class="mt-5">リクエストされた投稿</h4>
        <% n = 0 %>
        <table class="table">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>名前</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <% if post.status == "公開" %>
                <% @requests = post.requests %>
                <% if @requests %>
                  <% @requests.each do |request| %>
                    <% @post= request.post %>
                      <% n = 1 %>
                      <tr>
                        <td><%= link_to @post.title , contributor_post_path(@post) %></td>
                        <td>
                          <%= Recipient.find(request.recipient_id).name %>
                        </td>
                      </tr>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <% unless n == 1 %>
          <p>現在、リクエストはございません。</p>
        <% end %>
    </div>
    <div class="col-md-8 of">
      <h4 class="mt-5">投稿一覧</h4>
      <%= form_with(url: search_contributor_posts_path, method: :get, local: true) do |f| %>
        <%= f.label :title, "タイトル" %>
        <%= f.text_field :title, placeholder: 'タイトル', value: params[:title] %><br>
      
        <%= f.label :prefecture, "都道府県" %>
        <%= f.select :prefecture, options_for_select(Post.prefectures), value: params[:prefecture] %>
      
        <%= f.label :genre,"ジャンル" %>
        <%= f.select :genre, options_for_select(Post.genres), {include_blank: true}, value: params[:genre] %>
        
        <%= f.label :status,"ステータス" %>
        <%= f.select :status, options_for_select(Post.statuses), {include_blank: true}, value: params[:status] %>
        <%= submit_tag '検索', class: "btn btn-primary h-55 px-20 py-0 mt-0" %>
      <% end %>
      <%= render 'index', posts: @posts %>
    </div>
    <div class='p__paginate '><%= paginate @posts %></div>
  </div>
</div>

app/views/contributor/posts/new.html.erb
<div class="container">
  <div class ="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @post, url: contributor_posts_path, method: :post, local: true do |form| %>
        <%= render 'form' ,f: form %>
      <% end %>
    </div>
  </div>
</div>

app/views/contributor/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-7">
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <th class="post-th">投稿・更新日</th>
            <td><%= @post.updated_at.to_s(:datetime_jp) %></td>
          </tr>
          <tr>
            <th class="post-th">タイトル</th>
            <td><%= @post.title %></td>
          </tr>
          <tr>
            <th class="post-th">ジャンル</th>
            <td><%= @post.genre %></td>
          </tr>
          <tr>
            <th class="post-th">内容</th>
            <td><%= @post.content %></td>
          </tr>
          <tr>
            <th class="post-th">画像</th>
            <td><%= attachment_image_tag @post, :post_image, :fill, 125, 125, format: 'jpg',fallback: "noImage.png", size:'125x125' %></td>
          </tr>
          <tr>
            <th class="post-th">ステータス</th>
            <td><%= @post.status %></td>
          </tr>
          <tr>
            <th class="post-th">対象地域</th>
            <td><%= @post.prefecture %></td>
          </tr>
          <tr>
            <th class="post-th">ストック中のユーザー数</th>
            <td><%= @post.favorites.count %>人</td>
          </tr>
          <tr>
            <th class="post-th">リクエスト中のユーザー数</th>
            <td><%= @post.requests.count %>人</td>
          </tr>
        </tbody>
      </table>
        <div class="row">
          <div class="col-2"><%= link_to '編集', edit_contributor_post_path, class:"btn btn-primary btn-block" %></div>
          <% unless @post.rooms.exists? %>
          <div class="col-2"><%= link_to '削除', contributor_post_path(@post), method: :delete, data: { confirm: "【確認】投稿を削除してもよろしいですか？" }, class:"btn btn-danger btn-block " %></div>
          <% end %>
        </div>
      <div class="row">
        <%= link_to 'My投稿一覧へ戻る', contributor_posts_path ,class: "m-3" %>
      </div>
      </div>
    <div class="col-md-4 offset-md-1">
      <h4 class="mt-5">リクエストユーザー一覧</h4>
      <% if @post.requests.present? %>
        <table>
          <thead>
            <td class="w-25">名前</td>
            <td class="w-25">団体名</td>
            <tdclass="w-50"> </td>
          </thead>
          <tbody>
            <% @recipients.each do |recipient| %>
              <tr>
                <th><%= recipient.name %></th>
                <th><%= recipient.organization_name %></th>
                <th>
                  <% if @post.created_rooms?(recipient) %>
                    <%= link_to 'チャットルームへ', room_path(@post.rooms.find_by(recipient_id: recipient.id)),class:"btn btn-outline-secondary btn-block" %>
                  <% else %>
                    <%= form_with model: @room, url: rooms_path, method: :post, local: true do |f| %>
                      <%= f.hidden_field :post_id, value: @post.id %>
                      <%= f.hidden_field :recipient_id, value: recipient.id %>
                      <%= f.submit 'チャットルームを作る', class:"btn btn-outline-secondary btn-block" %>
                    <% end %>
                  <% end %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>リクエスト中のユーザはおりません。</p>
      <% end %>
    </div>
  </div>
</div>