config/routes.rb
Rails.application.routes.draw do
  devise_for :recipients, skip: [:registrations,:passwords], controllers: {
    sessions: 'recipient/sessions'
  }
  devise_for :contributors, skip: [:passwords], controllers: {
    registrations: 'contributor/registrations',
    sessions: 'contributor/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done',as: 'done'
  get '/about' => 'homes#about', as: 'about'

  namespace :contributor do
    resource :contributors do
      member do
        get :quit
        patch :out
      end
    end
    resources :posts do
      collection do
        get 'search'
      end
    end
  end

  scope module: :recipient do
    resources :recipients do
      get 'favorites' => 'favorites#index'
      get 'follows' => 'relationships#follows', as: 'follows'
    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
      collection do
        get 'search'
      end
    end
    resources :contributors do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end


  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :stocks, through: :favorites, source: :post
  has_many :requests, dependent: :destroy
  has_many :askings, through: :requests, source: :post
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :contributor
  has_many :rooms

  def follow(parameter)
    self.relationships.create(contributor_id: parameter)
  end

  def unfollow(parameter)
    self.relationships.find_by(contributor_id: parameter).destroy
  end

  def following?(contributor)
    self.followings.include?(contributor)
  end
end

app/controllers/recipient/confirmations_controller.rb
# frozen_string_literal: true

class Recipient::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/recipient/contributors_controller.rb
class Recipient::ContributorsController < ApplicationController
  def show
    @contributor = Contributor.find(params[:id])
    @recipient = current_recipient
    @posts = @contributor.posts.where(status: '公開').order(updated_at: :desc).page(params[:page]).per(15)
  end
end

app/controllers/recipient/favorites_controller.rb
class Recipient::FavoritesController < ApplicationController

  def create
    current_recipient.favorites.create(post_id: params[:post_id])
    redirect_to request.referer
  end

  def destroy
    current_recipient.favorites.find_by(post_id: params[:post_id]).destroy
    redirect_to request.referer
  end

  def index
    @recipient = current_recipient
    @posts = @recipient.stocks
  end


end

app/controllers/recipient/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Recipient::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/recipient/passwords_controller.rb
# frozen_string_literal: true

class Recipient::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/recipient/posts_controller.rb
class Recipient::PostsController < ApplicationController
  def index
    @posts = Post.where(status: '公開').order(updated_at: :desc).page(params[:page]).per(15)
  end

  def show
    @post = Post.find(params[:id])
    @contributor = @post.contributor
    @recipient = current_recipient
  end

  def search
    @posts = Post.search(params[:name],params[:title], params[:prefecture], params[:genre]).order(updated_at: :desc).page(params[:page]).per(15)
    render :index
  end
end

app/controllers/recipient/recipients_controller.rb
class Recipient::RecipientsController < ApplicationController
  def show
    @recipient = current_recipient
    @rooms = @recipient.rooms
  end

  def edit
    @recipient = current_recipient
  end

  def update
    @recipient = current_recipient
    if @recipient.update(recipient_params)
      redirect_to recipients_path
    else
      render :edit
    end
  end

  private

  def recipient_params
    params.require(:recipient).permit(:name, :email, :organization_name, :organization_url)
  end
end

app/controllers/recipient/registrations_controller.rb
# frozen_string_literal: true

class Recipient::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/recipient/relationships_controller.rb
class Recipient::RelationshipsController < ApplicationController

  def create
    @recipient = current_recipient
    @recipient.follow(params[:contributor_id])
    redirect_to request.referer
  end

  def destroy
    @recipient = current_recipient
    @recipient.unfollow(params[:contributor_id])
    redirect_to request.referer
  end

  def followers
    @contributor = Contributor.find(params[:contributor_id])
    @recipients = @contributor.followers
  end

  def follows
    @recipient = current_recipient
    @contributors = @recipient.followings
  end
end

app/controllers/recipient/requests_controller.rb
class Recipient::RequestsController < ApplicationController
  def create
    current_recipient.requests.create(post_id: params[:post_id])
    redirect_to request.referer
  end
end

app/controllers/recipient/sessions_controller.rb
# frozen_string_literal: true

class Recipient::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/recipient/unlocks_controller.rb
# frozen_string_literal: true

class Recipient::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/recipient/contributors_helper.rb
module Recipient::ContributorsHelper
end

app/helpers/recipient/favorites_helper.rb
module Recipient::FavoritesHelper
end

app/helpers/recipient/posts_helper.rb
module Recipient::PostsHelper
end

app/helpers/recipient/recipients_helper.rb
module Recipient::RecipientsHelper
end

app/helpers/recipient/relationships_helper.rb
module Recipient::RelationshipsHelper
end

app/helpers/recipient/requests_helper.rb
module Recipient::RequestsHelper
end

app/views/recipient/recipients/edit.html.erb
<div class="container my-5">
  <div class ="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @recipient, url: recipients_path, method: :patch, local: true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :organization_name %>
        <%= f.text_field :organization_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :organization_url %>
        <%= f.text_field :organization_url, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit '変更を保存' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipient/recipients/favorite_index.html.erb
<div>
  <% @favorites.each do |favorite| %>
    <% post = Post.find_by(id: favorite.post_id) %>
    <div>
      <%= post.updated_at.to_s(:day_jp) %>
    </div>
    <%= link_to post_path(post) do %>
      <div>
        <%= attachment_image_tag post, :post_image, :fill ,100 ,100 ,format: 'jpeg' %>
      </div>
      <div>
        <%= post.title %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipient/recipients/show.html.erb
<div class="container px-3 px-sm-0 mt-5">
  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <tr>
          <th>name</th>
          <td><%= @recipient.name %>
        </tr>
        <tr>
          <th>団体名</th>
        <% if @recipient.organization_url %>
        <td><%= link_to @recipient.organization_name, @recipient.organization_url %>
        <% else %>
        <td><%= @recipient.organization_name %>
        <% end %>
        </tr>
      </table>
      <% if recipient_signed_in? %>
        <div class="row">
        <%= link_to '編集', edit_recipient_path(@recipient), class:"btn btn-outline-secondary btn-block fas fa-user-cog w-25" %>
        </div>
        <div class="row">
          <%= link_to 'ストック一覧', recipient_favorites_path(@recipient),class: "m-3" %>
        </div>
      <% end %>
    </div>
    <div div class="col-md-4 offset-md-1">
      <h4>やり取り中のチャット一覧</h4>
      <table>
        <tbody>
          <% if @rooms %>
            <% @rooms.each do |room| %>
              <tr>
                <th>名前：<%= link_to Post.find(room.post_id).contributor.nickname, contributor_path(Post.find(room.post_id).contributor) %>　　</th>
                <th>チャット先：
                  <%= link_to room_path(room) do %>
                    <%= Post.find(room.post_id).title %>
                  <% end %>
                </th>
              </tr>
            <% end %>
          <% else %>
            <p>現在、やり取り中のチャットはございません。</p>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>