config/routes.rb
Rails.application.routes.draw do
  devise_for :recipients, skip: [:registrations,:passwords], controllers: {
    sessions: 'recipient/sessions'
  }
  devise_for :contributors, skip: [:passwords], controllers: {
    registrations: 'contributor/registrations',
    sessions: 'contributor/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done',as: 'done'
  get '/about' => 'homes#about', as: 'about'

  namespace :contributor do
    resource :contributors do
      member do
        get :quit
        patch :out
      end
    end
    resources :posts do
      collection do
        get 'search'
      end
    end
  end

  scope module: :recipient do
    resources :recipients do
      get 'favorites' => 'favorites#index'
      get 'follows' => 'relationships#follows', as: 'follows'
    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
      collection do
        get 'search'
      end
    end
    resources :contributors do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end


  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { 新規登録希望: 0, 退会希望: 1, その他: 2 }
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followers, through: :relationships, source: :recipient
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, :nickname, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :recipient
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :room_id, :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contributor
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :requesters, through: :requests, source: :recipient
  has_many :rooms
  attachment :post_image

  validates :contributor_id, :genre, :title, :status, :prefecture, presence: true

  enum prefecture: {
    指定地域なし:1,
    北海道:2,青森県:3,岩手県:4,宮城県:5,秋田県:6,山形県:7,福島県:8,
    茨城県:9,栃木県:10,群馬県:11,埼玉県:12,千葉県:13,東京都:14,神奈川県:15,
    新潟県:16,富山県:17,石川県:18,福井県:19,山梨県:20,長野県:21,
    岐阜県:22,静岡県:23,愛知県:24,三重県:25,
    滋賀県:26,京都府:27,大阪府:28,兵庫県:29,奈良県:30,和歌山県:31,
    鳥取県:32,島根県:33,岡山県:34,広島県:35,山口県:36,
    徳島県:37,香川県:38,愛媛県:39,高知県:40,
    福岡県:41,佐賀県:42,長崎県:43,熊本県:44,大分県:45,宮崎県:46,鹿児島県:47,沖縄県:48
  }

  enum status: {
    非公開:1, 公開:2,決定済み:3
  }

  enum genre: {
    その他:1, 寄付:2, 活動:3
  }

  def favorited_by?(recipient)
    favorites.where(recipient_id: recipient.id).exists?
  end

  def requested_by?(recipient)
    requests.where(recipient_id: recipient.id).exists?
  end

  def created_rooms?(recipient)
    rooms.where(recipient_id: recipient.id).exists?
  end

  def self.search(name, title, prefecture, genre)
    posts = Post.where(status: '公開').order(updated_at: :desc)
    if name.present?
      posts = posts.includes(:contributor).joins(:contributor).where('nickname LIKE?', "%#{name}%")
    end
    if title.present?
      posts = posts.where('title LIKE?', "%#{title}%")
    end
    if genre.present?
      posts = posts.where(genre: genre)
    end
    if prefecture == '1'
      posts
    else
      posts =  posts.where(prefecture: [prefecture, 1])
    end
  end

  def self.search_contributor_post(title, prefecture, genre, status)
    posts = self.order(updated_at: :desc)
    if title.present?
      posts = posts.where('title LIKE?', "%#{title}%")
    end
    if genre.present?
      posts = posts.where(genre: genre)
    end
    if status.present?
      posts = posts.where(status: status)
    end
    if prefecture == '1'
      posts
    else
      posts =  posts.where(prefecture: [prefecture, 1])
    end
  end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :stocks, through: :favorites, source: :post
  has_many :requests, dependent: :destroy
  has_many :askings, through: :requests, source: :post
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :contributor
  has_many :rooms

  def follow(parameter)
    self.relationships.create(contributor_id: parameter)
  end

  def unfollow(parameter)
    self.relationships.find_by(contributor_id: parameter).destroy
  end

  def following?(contributor)
    self.followings.include?(contributor)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :recipient
  belongs_to :contributor

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :recipient
  belongs_to :post
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :recipient
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # bofore_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    case resource
    when Contributor
      contributor_contributors_path
    when Recipient
      recipient_path(current_recipient)
    end
  end
  # def configure_permitted_parameters
  # end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def confirm
    @contact = Contact.new(contact_params)
  end
  
  def back
    @contact = Contact.new(contact_params)
    render :new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver
      redirect_to done_path
    else
      render :new
    end
  end
  
  def done
  end
  
  private
  
  def contact_params
    params.require(:contact).permit(:name, :organization_name, :email, :phone_number, :subject, :content)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    @message.room_id = params[:room_id]
    unless recipient_signed_in?
      @message.is_recipient = false
    end
    if @message.save
      redirect_to request.referer
    else
      @room = Room.find(params[:room_id])
      @recipient = Recipient.find(@room.recipient_id)
      @post = Post.find(@room.post_id)
      @contributor = Contributor.find(@post.contributor_id)
      @messages = Message.where(room_id: @room.id)
      render 'rooms/show'
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.new
    @room.post_id = params[:room][:post_id]
    @room.recipient_id = params[:room][:recipient_id]
    if @room.save
      redirect_to room_path(@room)
    else
      redirect_to request.referer
    end
  end

  def show
    @room = Room.find(params[:id])
    @recipient = Recipient.find(@room.recipient_id)
    @post = Post.find(@room.post_id)
    @contributor = Contributor.find(@post.contributor_id)
    @messages = Message.where(room_id: @room.id).page(params[:page]).per(10)
    @message = Message.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contributor/posts_helper.rb
module Contributor::PostsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recipient/posts_helper.rb
module Recipient::PostsHelper
end

app/helpers/recipient/requests_helper.rb
module Recipient::RequestsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/contacts/done.html.erb
<h1>送信完了</h1>

app/views/contacts/new.html.erb
<div class="overflow">
  <h4>お問い合わせフォーム</h4>
  <% unless recipient_signed_in? || contributor_signed_in? %>
    <p>寄付が必要な方はこのフォームからお問い合わせお願いします。</p>
  <% end %>
  <% if contributor_signed_in? %>
    <span>寄付をする方の退会は</span><%= link_to 'こちら', quit_contributor_contributors_path %>
  <% end %>
<%= form_with model: @contact do |f| %>
  <div class="row mt-3">
    <%= f.label :name, class:"offset-1 col-2" %>
    <%= f.text_field :name, autofocus: true, class:"col-3" %>
  </div>

  <div class="row mt-3">
    <%= f.label :organization_name, class:"offset-1 col-2" %>
    <%= f.text_field :organization_name, class:"col-3" %>
  </div>

  <div class="row mt-3">
    <%= f.label :email, class:"offset-1 col-2" %>
    <%= f.text_field :email, class:"col-3" %>
  </div>

  <div class="row mt-3">
    <%= f.label :phone_number, class:"offset-1 col-2" %>
    <%= f.text_field :name, class:"col-3" %>
  </div>

  <div class="row mt-3">
    <%= f.label :subject, class:"offset-1 col-2" %>
    <%= f.select :subject, Contact.subjects.keys, class:"col-3" %>
  </div>


  <div class="row mt-3">
    <%= f.label :content, class:"offset-1 col-2" %>
    <%= f.text_area :content, size: "1x15", class:"col-3" %>
  </div>

  <div class="actions offset-3 mt-3 mb-4">
    <td></td><td></td><%= f.submit '送信', class:"btn btn-success btn-lg" %>
  </div>
<% end %>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-lg-12">
      <div class="card chat-app">
        <div id="plist" class="people-list">
          <ul class="list-unstyled chat-list mt-2 mb-0">
            <p>チャット一覧</p>
            <% if recipient_signed_in? %>
              <% n = 0 %>
              <% current_recipient.rooms.each do |room| %>
                <% if room.chat_status %>
                  <% n+=1 %>
                　<% if room != @room %>
                    <li class="clearfix">
                      <div class="about">
                        <div class="name">
                          <%= link_to Post.find(room.post_id).contributor.nickname, contributor_path(Post.find(room.post_id).contributor) %>
                        </div>
                        <div class="status">
                          <%= link_to room_path(room) do %>
                            <%= Post.find(room.post_id).title %>
                          <% end %>
                        </div>
                      </div>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            <% else contributor_signed_in? %>
              <% n = 0 %>
              <% current_contributor.posts.each do |post| %>
                <% if post.rooms.present? %>
                  <% post.rooms.each do |room| %>
                    <% if room.chat_status %>
                      <% n += 1 %>
                      <% if room != @room %>
                        <li class="clearfix">
                          <div class="about">
                            <div class="name">
                              <%= room.recipient.name %>
                            </div>
                            <div class="status">
                              <%= link_to room_path(room) do %>
                                <%= post.title %>
                              <% end %>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
            <% if n == 1 || n==0 %>
              <li class="clearfix">
                <div class="about">ほかにやり取り中のチャットはございません</div>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="chat">
          <% if recipient_signed_in? %>
            <div class="chat-header clearfix">
              <div class="row">
                <div class="col-lg-6">
                  <h2><%= @post.title %>のチャットルーム</h2>
                  <h4><%= @contributor.nickname %>とのチャット</h4>
                </div>
              </div>
            </div>
            <div class="chat-history">
              <ul class="m-b-0">
                <% d = "" %>
                <% @messages.each do |message| %>
                  <% if message.is_recipient %>
                    <li class="clearfix">
                      <div class="message-data">
                        <span class="message-data-time">
                          <% unless d == message.created_at.to_s(:year_jp) %>
                            <%= message.created_at.to_s(:year_jp) %>
                            <% d = message.created_at.to_s(:year_jp) %>
                          <% end %>
                          <%= message.created_at.to_s(:hour_jp) %>
                        </span>
                        <div><%= @recipient.name %></div>
                      </div>
                      <div class="message my-message">
                        <%= message.content %>
                      </div>
                    </li>
                  <% else %>
                    <li class="clearfix">
                      <div class="message-data text-right">
                        <span class="message-data-time">
                          <% unless d == message.created_at.to_s(:year_jp) %>
                            <%= message.created_at.to_s(:year_jp) %>
                            <% d = message.created_at.to_s(:year_jp) %>
                          <% end %>
                          <%= message.created_at.to_s(:hour_jp) %>
                        </span>
                        <div><%= attachment_image_tag @contributor, :profile_image, :fill, 50, 50, format: 'jpg',fallback: "no-imageuser.png", size:'50x50' %></div>
                      </div>
                      <div class="message other-message float-right">
                        <%= message.content %>
                      </div>
                    </li>
                  <% end %>
                <% end %>
                <div class='p__paginate '><%= paginate @messages %></div>
              </ul>
            </div>
          <% elsif contributor_signed_in? %>
            <div class="chat-header clearfix">
              <div class="row">
                <div class="col-lg-6">
                  <h2><%= @post.title %>のチャットルーム</h2>
                  <h4><%= @recipient.name %>とのチャット</h4>
                </div>
              </div>
            </div>
            <div class="chat-history">
              <ul class="m-b-0">
                <% d = "" %>
                <% @messages.each do |message| %>
                  <% if !(message.is_recipient) %>
                    <li class="clearfix">
                      <div class="message-data">
                        <span class="message-data-time">
                          <% unless d == message.created_at.to_s(:year_jp) %>
                            <%= message.created_at.to_s(:year_jp) %>
                            <% d = message.created_at.to_s(:year_jp) %>
                          <% end %>
                          <%= message.created_at.to_s(:hour_jp) %>
                          <div><%= attachment_image_tag @contributor, :profile_image, :fill, 50, 50, format: 'jpg',fallback: "no-imageuser.png", size:'50x50' %></div>
                        </span>
                      </div>
                      <div class="message my-message">
                        <%= message.content %>
                      </div>
                    </li>
                  <% else %>
                    <li class="clearfix">
                      <div class="message-data text-right">
                        <span class="message-data-time">
                          <% unless d == message.created_at.to_s(:year_jp) %>
                            <%= message.created_at.to_s(:year_jp) %>
                            <% d = message.created_at.to_s(:year_jp) %>
                          <% end %>
                          <%= message.created_at.to_s(:hour_jp) %>
                        </span>
                        <div><%= @recipient.name %></div>
                      </div>
                      <div class="message other-message float-right">
                        <%= message.content %>
                      </div>
                    </li>
                  <% end %>
                <% end %>
                <div class='p__paginate '><%= paginate @messages %></div>
              </ul>
            </div>
          <% end %>
          <div class="chat-message clearfix">
            <div class="input-group mb-0">
              <%= form_with model: @message, url: room_messages_path(@room), method: :post, local: true do |f| %>
                <div class="input-group-prepend">
                  <%= f.button :type => "submit", class: 'input-group-text' do  %>
                    <i class="fas fa-paper-plane"></i>
                  <% end %>
                  <%= f.text_field :content, :size=>"100", class:"form-control" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>