config/routes.rb
Rails.application.routes.draw do
  devise_for :recipients, skip: [:registrations,:passwords], controllers: {
    sessions: 'recipient/sessions'
  }
  devise_for :contributors, skip: [:passwords], controllers: {
    registrations: 'contributor/registrations',
    sessions: 'contributor/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done',as: 'done'
  get '/about' => 'homes#about', as: 'about'

  namespace :contributor do
    resource :contributors do
      member do
        get :quit
        patch :out
      end
    end
    resources :posts do
      collection do
        get 'search'
      end
    end
  end

  scope module: :recipient do
    resources :recipients do
      get 'favorites' => 'favorites#index'
      get 'follows' => 'relationships#follows', as: 'follows'
    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
      collection do
        get 'search'
      end
    end
    resources :contributors do
      resource :relationships, only: [:create, :destroy]
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end


  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { 新規登録希望: 0, 退会希望: 1, その他: 2 }
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followers, through: :relationships, source: :recipient
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, :nickname, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :recipient
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :room_id, :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contributor
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :requesters, through: :requests, source: :recipient
  has_many :rooms
  attachment :post_image

  validates :contributor_id, :genre, :title, :status, :prefecture, presence: true

  enum prefecture: {
    指定地域なし:1,
    北海道:2,青森県:3,岩手県:4,宮城県:5,秋田県:6,山形県:7,福島県:8,
    茨城県:9,栃木県:10,群馬県:11,埼玉県:12,千葉県:13,東京都:14,神奈川県:15,
    新潟県:16,富山県:17,石川県:18,福井県:19,山梨県:20,長野県:21,
    岐阜県:22,静岡県:23,愛知県:24,三重県:25,
    滋賀県:26,京都府:27,大阪府:28,兵庫県:29,奈良県:30,和歌山県:31,
    鳥取県:32,島根県:33,岡山県:34,広島県:35,山口県:36,
    徳島県:37,香川県:38,愛媛県:39,高知県:40,
    福岡県:41,佐賀県:42,長崎県:43,熊本県:44,大分県:45,宮崎県:46,鹿児島県:47,沖縄県:48
  }

  enum status: {
    非公開:1, 公開:2,決定済み:3
  }

  enum genre: {
    その他:1, 寄付:2, 活動:3
  }

  def favorited_by?(recipient)
    favorites.where(recipient_id: recipient.id).exists?
  end

  def requested_by?(recipient)
    requests.where(recipient_id: recipient.id).exists?
  end

  def created_rooms?(recipient)
    rooms.where(recipient_id: recipient.id).exists?
  end

  def self.search(name, title, prefecture, genre)
    posts = Post.where(status: '公開').order(updated_at: :desc)
    if name.present?
      posts = posts.includes(:contributor).joins(:contributor).where('nickname LIKE?', "%#{name}%")
    end
    if title.present?
      posts = posts.where('title LIKE?', "%#{title}%")
    end
    if genre.present?
      posts = posts.where(genre: genre)
    end
    if prefecture == '1'
      posts
    else
      posts =  posts.where(prefecture: [prefecture, 1])
    end
  end

  def self.search_contributor_post(title, prefecture, genre, status)
    posts = self.order(updated_at: :desc)
    if title.present?
      posts = posts.where('title LIKE?', "%#{title}%")
    end
    if genre.present?
      posts = posts.where(genre: genre)
    end
    if status.present?
      posts = posts.where(status: status)
    end
    if prefecture == '1'
      posts
    else
      posts =  posts.where(prefecture: [prefecture, 1])
    end
  end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :stocks, through: :favorites, source: :post
  has_many :requests, dependent: :destroy
  has_many :askings, through: :requests, source: :post
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :contributor
  has_many :rooms

  def follow(parameter)
    self.relationships.create(contributor_id: parameter)
  end

  def unfollow(parameter)
    self.relationships.find_by(contributor_id: parameter).destroy
  end

  def following?(contributor)
    self.followings.include?(contributor)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :recipient
  belongs_to :contributor

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :recipient
  belongs_to :post
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :recipient
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # bofore_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    case resource
    when Contributor
      contributor_contributors_path
    when Recipient
      recipient_path(current_recipient)
    end
  end
  # def configure_permitted_parameters
  # end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def confirm
    @contact = Contact.new(contact_params)
  end
  
  def back
    @contact = Contact.new(contact_params)
    render :new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver
      redirect_to done_path
    else
      render :new
    end
  end
  
  def done
  end
  
  private
  
  def contact_params
    params.require(:contact).permit(:name, :organization_name, :email, :phone_number, :subject, :content)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    @message.room_id = params[:room_id]
    unless recipient_signed_in?
      @message.is_recipient = false
    end
    if @message.save
      redirect_to request.referer
    else
      @room = Room.find(params[:room_id])
      @recipient = Recipient.find(@room.recipient_id)
      @post = Post.find(@room.post_id)
      @contributor = Contributor.find(@post.contributor_id)
      @messages = Message.where(room_id: @room.id)
      render 'rooms/show'
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.new
    @room.post_id = params[:room][:post_id]
    @room.recipient_id = params[:room][:recipient_id]
    if @room.save
      redirect_to room_path(@room)
    else
      redirect_to request.referer
    end
  end

  def show
    @room = Room.find(params[:id])
    @recipient = Recipient.find(@room.recipient_id)
    @post = Post.find(@room.post_id)
    @contributor = Contributor.find(@post.contributor_id)
    @messages = Message.where(room_id: @room.id).page(params[:page]).per(10)
    @message = Message.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</p>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-white pt-5 pb-4 footer-color">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-4">
        <p>寄付で気持ちをあげよう！</p>
        <%= image_tag('logo.png') %>
      </div>
      <div class="col-md-8">
        <h6 class="text-white mt-2 mb-3"><%= link_to "お問い合わせ", new_contact_path,class: "text-white-50" %></h6>
        <ul class="p-0 list-unstyled">
          <li>
            <%= link_to 'about', about_path,class: "text-white-50" %>
          </li>
          <li>
            <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm header-color">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to root_path(class:"navbar-brand p-3") do %>
        <%= image_tag('logo.png') %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if contributor_signed_in? %>
            <li class="nav-item">
              <%= link_to 'マイページ', contributor_contributors_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', posts_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to '新規投稿', new_contributor_post_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_contributor_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
          <% elsif recipient_signed_in? %>
            <li class="nav-item">
              <%= link_to 'マイページ', recipient_path(current_recipient), class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'フォロー一覧', recipient_follows_path(current_recipient), class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', posts_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_recipient_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to '投稿一覧', posts_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログイン(寄付をする方)', new_contributor_session_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログイン(寄付が必要な方)', new_recipient_session_path, class: 'nav-link text-white' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AGEYO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body class="d-flex flex-column vh-100 w-100">
    <div class="main-color">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>